# Generated by Django 4.2.3 on 2023-10-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_salida', models.DateTimeField()),
            ],
        ),
    ]
